### ISSUE TITLE
Hi, one question

### ISSUE THREAD

**Issue by kallookoo** [kallookoo/WebSearch#1]
Hi,
You transfer it to me and I take charge of it to support version 3 of sublime text?
Thanks

**Comment by catalinc** [comment]
Hi,

Yeah, sure. I'm not using ST anymore anyway.

**Comment by catalinc** [comment]
I tried to transfer but kallookoo/WebSearch already exists. Do you still want ownership?

**Comment by kallookoo** [comment]
Yes, I'll erase my fork and transfer them to me when you can, thanks

**Comment by catalinc** [comment]
Transfer in progress...  Enjoy :-)

**Comment by kallookoo** [comment]
Thanks!!!
